### ISSUE TITLE
[BUG] Can't start "Envoys, Wineboys" quest to begin BaW DLC

### ISSUE THREAD

**Issue by efierros** [Aelto/tw3-random-encounters-reworked#101]
**Describe the bug**
When I try to start the quest "Envoys, Wineboys" to begin BaW DLC, I can't obtain the quest from the board, all of the boards has the quest for RER but the needed itsn't. I know it's the mod beacuase I commented the function call from bootstap registry and it works.

**To Reproduce**
1. Try to get the quest "Envoys, Wineboys" from any board

**Expected behavior**
I think that the expected behavior is to see on board both quests, the one for RER and the one to "Envoys, Wineboys"

**Screenshots**

**Random Encounters version used:**
 RER V2.8.0 used.

**Mods you use:**
 - Random Encounters Reworked

**Comment by Aelto** [comment]
Hello,

The mod now hides vanilla quests from the board as part of the contract system feature. You can read more about it on [this page](https://aelto.github.io/tw3-random-encounters-reworked/rer-bible/contracts/index.html) in the last paragraph. If you wish to disable the feature you can set the required reputation slider to 0 and after a reload everything will be back to vanilla.

Unless you mean it doesn't appear even after completing at least two RER contracts ?

**Comment by efierros** [comment]
Ohhh I see, sorry to bother you with such a silly thing, gonna read more carefully next time before asumming it was a bug.

Thank you

**Comment by Aelto** [comment]
You're welcome and no issues, the mod is getting filled with obscure features so i understand it perfectly!
