### ISSUE TITLE
[BUG] Monsters in HoS DLC (Iris painted world)

### ISSUE THREAD

**Issue by cyl3x** [Aelto/tw3-random-encounters-reworked#102]
**Describe the bug**
It's not really a bug, the mod itself works. But monsters also spawn in special areas, like Iris Everec painted world, which in my opinion really breaks the immersion. And disabling the mod in its menu section dont despawn already created creatures/footprints.

**To Reproduce**
1. Play Iris Everec paited world

**Expected behavior**
Maybe considering not generating creatures in such scenes, if it is not already happening and the Iris paiting is the only place :)

**Random Encounters version used:**
 RER V2.8.0 used.

**Additional context**
I really like your mod :)

**Comment by Aelto** [comment]
Hello!

Thank you for the issue, and the additional context :)

I agree the mod should be entirely disabled in that region of the game. I added it to the backlog for the release v2.9 i'm preparing. It's a release already packed with content so it may take some time before i start working on this issue.

**Comment by cyl3x** [comment]
Oh nice, i will keep the command in mind for the next time :)

**Comment by Aelto** [comment]
Hi,

The mod should no longer spawn creatures in these areas anymore. The fix is included in [the v2.9 pre-release 1](https://github.com/Aelto/tw3-random-encounters-reworked/releases/tag/v2.9-pre-release_1) if you're interested.

Thanks for the report!
