### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SneakyEvil0** [Aelto/tw3-random-encounters-reworked#114]
Hi i got some random crash on the mod.Can someone help me out to fix this.Here a sample of my crashlog 
Crash reason: EXCEPTION_ACCESS_VIOLATION (3221225477), Error writing location 0x000001f0

Crashed Thread:

Thread ID: 4584

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x23cf29 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xa2013f - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x519cd7 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x1d11ce - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x1d1fcd - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x3a60c - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x6bfb5 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x6a7e4 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x1a30b4 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x1891f5 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x66feec - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x58cdf2 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x58d729 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x1adbec - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x223281 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x224600 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x11014d - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x6e6634 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0xc86b6 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xeeec4 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0xc396a - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xef1c7 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x1216 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x428ad - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x166f - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x196c - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x23dcf8 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

Debug Information
================================================================

Commandline: "C:\Program Files (x86)\Steam\steamapps\common\The Witcher 3\bin\x64\witcher3.exe" 

Thread ID: 11960

callstack:
CreateDispatcherQueueController() + 0x12039 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x117c1 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x10a94 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x13cbb - <Unknown File>(0)
CreateDispatcherQueueController() + 0x10f78 - <Unknown File>(0)
CoreUICreateEx() + 0x1a15 - <Unknown File>(0)
CoreUICreateEx() + 0x89b - <Unknown File>(0)
Ordinal2604() + 0x3a7a - <Unknown File>(0)
DllGetActivationFactory() + 0x4109 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14300

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb94e07 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 22568

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17372

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 16600

callstack:
DllUnregisterServer() + 0x45ad - <Unknown File>(0)
DllUnregisterServer() + 0x48a6 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 20012

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17504

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9856

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 11328

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 7260

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 10792

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 22212

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 1524

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbd88c - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 19656

callstack:
Scaleform::System::~System() + 0x7f1be7 - <Unknown File>(0)
Scaleform::System::~System() + 0x7f1ca0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 25176

callstack:
Scaleform::System::~System() + 0x7f1be7 - <Unknown File>(0)
Scaleform::System::~System() + 0x7f1ca0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 11848

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4420 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x2463a7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24654e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 24080

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17480

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 15908

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 24344

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14080

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 4668

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 23576

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 3300

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 23776

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 7108

callstack:
NVDEV_Thunk() + 0x893c8a - <Unknown File>(0)
NVDEV_Thunk() + 0x8889fd - <Unknown File>(0)
NVDEV_Thunk() + 0x2788da - <Unknown File>(0)
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 24892

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 25020

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 23828

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 12000

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 21720

callstack:
OpenAdapter12() + 0x5b2f48 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Game

Last opened world: novigrad.w2w

================================================================

Game

Last opened world: novigrad.w2w

================================================================

**Comment by Aelto** [comment]
Crash logs provide no useful information unfortunately, could you describe what you were doing before the crashes ?

**Comment by SneakyEvil0** [comment]
I was fast travelling to another then it crashed.It happen really much but like i said its really random

**Comment by Aelto** [comment]
I'll need you to complete the template you skipped and replaced with the crashlog, as i need the information before i can do anything. Could you please it?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Random Encounters version used:**
 RER V0.0.0 used.

**Mods you use:**
 - Random Encounters Reworked
 - _other mods you use..._

**Additional context**
Add any other context about the problem here.

**Comment by Aelto** [comment]
closing for #115
