### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DameonBlackThorn** [Aelto/tw3-random-encounters-reworked#121]
followed the instruction and placed the installer in the witcher 3 file and ran it with powershell and after it finished i tried to run the game and got this message
![crash report](https://user-images.githubusercontent.com/108980120/178102184-f391beb0-6b09-42a8-9129-6b286e288c90.jpg)
 
 
 and i have no idea how to fix the issue

**Comment by Aelto** [comment]
Hi,

Could you please share the other mods you use?

**Comment by DameonBlackThorn** [comment]
Always full xp
Autowin Gwent
Gwent - maxbet 100000
More money for traders 
No item levels 
Rare items merchant 
Increased creature loot ultimate 

I thought their may be a conflict with one of these mods so I took them all out and tried to install with a clean slate and it still didn't work.

**Comment by ADawesomeguy** [comment]
Are you positive it's not a merge error?

**Comment by Magoo76** [comment]
Hey, almost same issue as above : [https://puu.sh/JgaI2/86a6016f08.png](url)
I have to add I installed RER manually, the powershell wouldn't work for me for some reason, and I have W3EE / W3EE Redux / patch base / patch bootstrap + bootstrap registry / RER (ofc) and a bunch of sharedutils mods that came with RER. Finally I have the RER patch for EE and no merge. I tried merging stuff but it gets worse ahah.

**Comment by Aelto** [comment]
> Hey, almost same issue as above : 
> 
> Error [modw3ee]local\w3ee - imports.ws(91): Class 'CClothComponent' was already exported.
> Error [modw3ee]local\w3ee - imports.ws(166): Class 'CDestructionSystemComponent' was already exported.
> Error [modw3ee]local\w3ee - imports.ws(232): Class 'CDestructionComponent' was already exported.
> Error [modw3ee]local\w3ee - imports.ws(637): Class 'CSoundAmbientAreaComponent' was already exported.
> 
> I have to add I installed RER manually, the powershell wouldn't work for me for some reason, and I have W3EE / W3EE Redux / patch base / patch bootstrap + bootstrap registry / RER (ofc) and a bunch of sharedutils mods that came with RER. Finally I have the RER patch for EE and no merge. I tried merging stuff but it gets worse ahah.
> 
> Edit: I reinstalled everything, and with only RER and it's dependencies I got the same errors.

You have to merge the mods, even with RER alone. For example SharedImports and one of the sharedutils have conflicts you must merge. With EE you are not expected to have SharedImports as it already has the changes bundled in the overhaul.

**Comment by Magoo76** [comment]
Ok but with EE and Redux what should I merge ? since I have the patch for EE. Does Redux counts as EE or should I merge Redux and sharedutils? 

I'll try again with just RER first though.

**Comment by Magoo76** [comment]
Hey, I finally managed to launch the game !! I had to keep both pieces of script between Redux and sharedtulis_npcInteraction on the merge for the file playerInput.ws.
I went for sharedutils first then Redux, is that ok? It will work right? I have the menu for RER in my game's menu btw.

**Comment by crimsonblod** [comment]
> Hey, I finally managed to launch the game !! I had to keep both pieces of script between Redux and sharedtulis_npcInteraction on the merge for the file playerInput.ws. I went for sharedutils first then Redux, is that ok? It will work right? I have the menu for RER in my game's menu btw.
> 
> Edit : I'm a dumbass, I didn't see the merge details on the complete written guide, I'm going to follow this rn, I'm sorry :(
> 
> Edit 2 : oh the written guide says to do exactly what I did lol

This appears to have been the fix for me as well.
