### ISSUE TITLE
[BUG] Mod not working on 4.00 next gen patch

### ISSUE THREAD

**Issue by janakrajsrivastava** [Aelto/tw3-random-encounters-reworked#160]
**Describe the bug**
Mod not working on 4.00 next gen patch. I am not able to use install-script or carry on manual install to get the mod working.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Random Encounters version used:**
 RER V2.3 used.

**Mods you use:**
 - Random Encounters Reworked

**Additional context**

**Comment by Aelto** [comment]
Hello, the mod was just updated for NextGen. You can refer to the install instructions to install the mod!

**Comment by janakrajsrivastava** [comment]
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(60): Unable to find suitable operator 'OperatorLogicAnd' for given types (void, String)
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(85): Property 'comboStatus' exists but was not imported from C++ code.
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(116): Property 'comboStatus' exists but was not imported from C++ code.
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(151): I dont know any 'Platform_PS5'
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(164): I dont know any 'Platform_PS5'
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(307): I dont know any 'Platform_PS5'
Error [content0]game\gui\main_menu\ingamemenu\igmutilities.ws(425): I dont know any 'Platform_PS5'
Error [content0]game\localizedcontent.ws(28): I dont know any 'Platform_PS5'
Error [content0]game\localizedcontent.ws(38): I dont know any 'Platform_Xbox_SCARLETT_ANACONDA'
Error [content0]game\localizedcontent.ws(39): I dont know any 'Platform_Xbox_SCARLETT_LOCKHART'
Error [content0]game\quests\quest_function.ws(8865): I dont know any 'Platform_PS5'
Error [content0]game\quests\quest_function.ws(8976): I dont know any 'DT_SSD'
Error [content0]game\scenes\scene_functions.ws(1124): I dont know any 'DT_SSD'
Error [content0]game\gameplay\ghosts\ghost.ws(39): Function 'HapticStart' does not take 1 param(s)
Error [mod_sharedutils_mappins]game\player\r4player.ws(10077): Function 'HapticStart' does not take 1 param(s)
Error [content0]game\player\playerwitcher.ws(497): Function 'ClearTriggerEffect' does not take 1 param(s)
Error [content0]game\player\playerwitcher.ws(498): Function 'ClearTriggerEffect' does not take 1 param(s)
Error [content0]game\player\playerwitcher.ws(1910): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1911): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1945): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1966): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1973): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1974): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1986): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(1987): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(2003): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(2014): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(2018): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(2076): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(2077): Function 'SetTriggerEffect' does not take 3 param(s)
Error [content0]game\player\playerwitcher.ws(3479): Function 'HapticStart' does not take 1 param(s)
Error [content0]game\player\playerwitcher.ws(3485): Function 'HapticStart' does not take 1 param(s)
Error [content0]game\player\playerwitcher.ws(3492): Function 'HapticStart' does not take 1 param(s)
Error [content0]game\projectile\playerboltprojectile.ws(254): I dont know any 'Platform_PS5'
Error [content0]game\gameplay\items\itementity.ws(458): Function 'HapticStart' does not take 1 param(s)
Error [content0]game\gameplay\items\itementity.ws(464): Function 'HapticStart' does not take 1 param(s)
Error [content0]game\commongame.ws(347): Could not find function 'UpdateAO2CorrespondRT'
Error [content0]game\photomodemanager.ws(103): Could not find function 'Activate'
Error [content0]game\photomodemanager.ws(131): Function 'PauseGameplayFx' does not take 1 param(s)
Error [content0]game\photomodemanager.ws(137): Function 'PauseGameplayFx' does not take 1 param(s)
Error [content0]game\gui\main_menu\autosavewarningmenu.ws(38): I dont know any 'Platform_Xbox_SCARLETT_ANACONDA'
Error [content0]game\gui\main_menu\autosavewarningmenu.ws(39): I dont know any 'Platform_Xbox_SCARLETT_LOCKHART'
Error [content0]game\gui\main_menu\autosavewarningmenu.ws(45): I dont know any 'Platform_PS5'
Error [content0]game\gui\main_menu\ingamemenu.ws(1344): To few params in call to function 'LoadGameInit'
Error [content0]game\gui\menus\photomodemenu.ws(36): Could not find function 'SetPhotomodeMenu'
Error [content0]game\gui\menus\photomodemenu.ws(37): Could not find function 'SetEnabled'
Error [content0]game\gui\menus\photomodemenu.ws(45): Could not find function 'SetEnabled'
Error [content0]game\gui\menus\photomodemenu.ws(53): Could not find function 'SetFov'
Error [content0]game\gui\menus\photomodemenu.ws(56): Could not find function 'SetTilt'
Error [content0]game\gui\menus\photomodemenu.ws(59): Could not find function 'SetExposure'
Error [content0]game\gui\menus\photomodemenu.ws(62): Could not find function 'SetHighlights'
Error [content0]game\gui\menus\photomodemenu.ws(65): Could not find function 'SetSaturation'
Error [content0]game\gui\menus\photomodemenu.ws(68): Could not find function 'SetVignette'
Error [content0]game\gui\menus\photomodemenu.ws(71): Could not find function 'SetContrast'
Error [content0]game\gui\menus\photomodemenu.ws(74): Could not find function 'SetTemperature'
Error [content0]game\gui\menus\photomodemenu.ws(77): Could not find function 'SetChromaticAberration'
Error [content0]game\gui\menus\photomodemenu.ws(80): Could not find function 'SetFilmGrain'
Error [content0]game\gui\menus\photomodemenu.ws(85): Could not find function 'SetDofEnabled'
Error [content0]game\gui\menus\photomodemenu.ws(89): Could not find function 'SetDofEnabled'
Error [content0]game\gui\menus\photomodemenu.ws(93): Could not find function 'SetAperture'
Error [content0]game\gui\menus\photomodemenu.ws(96): Could not find function 'SetFocusDistance'
Error [content0]game\gui\menus\photomodemenu.ws(101): Could not find function 'SetAutoFocus'
Error [content0]game\gui\menus\photomodemenu.ws(105): Could not find function 'SetAutoFocus'
Error [content0]game\gui\menus\photomodemenu.ws(254): Could not find function 'GetFocusDistance'
Error [content0]game\gui\menus\photomodemenu.ws(261): Could not find function 'GetExposure'
Error [content0]game\gui\menus\photomodemenu.ws(262): Could not find function 'GetContrast'
Error [content0]game\gui\menus\photomodemenu.ws(263): Could not find function 'GetHighlights'
Error [content0]game\gui\menus\photomodemenu.ws(264): Could not find function 'GetTemperature'
Error [content0]game\gui\menus\photomodemenu.ws(265): Could not find function 'GetSaturation'
Error [content0]game\gui\menus\photomodemenu.ws(266): Could not find function 'GetChromaticAberration'
Error [content0]game\gui\popups\overlaypopup.ws(70): Could not find function 'GetIngameMenu'
Error [content0]game\gui\popups\overlaypopup.ws(139): Could not find function 'GetIngameMenu'

Warning [modsharedimports]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
Warning [modsharedimports]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.



i used the latest install-script and merged it using script merger. i received the above error messages. 
[message.txt](https://github.com/Aelto/tw3-random-encounters-reworked/files/10303582/message.txt)
