### ISSUE TITLE
[BUG] RER V3.0.0 : Scripts compiling errors at launch

### ISSUE THREAD

**Issue by HakanFly** [Aelto/tw3-random-encounters-reworked#161]
Hello,

Before that, I apologize. This ticket may be declared too early.
But I'm doing it in case it helps.

**Describe the bug**
The game with latest patch not launching.
Scripts compiling errors :
`Error [modrandomencountersreworked]local\rer_scripts.min.ws(16573): Latent function 'runManagerPreset' can be called only from inside of state entry or latent function`

**To Reproduce**
Manually install

**Expected behavior**

1. Remove the call to latent function this.runManagerPreset('Vanilla') line 16573 to pass scripts compilation.
2. Maybe it's not necessary to run this code when it's the 1st install.

**Random Encounters version used:**
 RER V3.0.0 used.

**Mods you use:**
 - Random Encounters Reworked
 - Friendly HUD
 - SCAAR
 - and others

**Additional context**
I never install or use this mod before.

Good luck and thank you for the awesome mod and update wip :)

**Comment by Aelto** [comment]
Thank you for the report, i updated the [release](https://github.com/Aelto/tw3-random-encounters-reworked/releases/tag/v3.0) assets to include the fix for the error you showed. Using the install script or installing manually again should resolve it.

**Comment by HakanFly** [comment]
I confirm. Thank you
