### ISSUE TITLE
Script error at launch. 

### ISSUE THREAD

**Issue by DOOMOlivera** [Aelto/tw3-random-encounters-reworked#162]
![Captura de pantalla (561)](https://user-images.githubusercontent.com/117670074/209363975-03c869dc-a53d-4fa9-8d0a-ee17957aaa6a.png)

My merges: 
![Captura de pantalla (562)](https://user-images.githubusercontent.com/117670074/209364040-eb62e0f3-f535-4a62-9402-b2e8dcd87074.png)

What could be causing the issue?

**Comment by Aelto** [comment]
@DOOMOlivera Thank you for the report, i updated the [release](https://github.com/Aelto/tw3-random-encounters-reworked/releases/tag/v3.0) assets to include the fix for the error you showed. Using the install script or installing manually again should resolve it!

**Comment by DOOMOlivera** [comment]
> @DOOMOlivera Thank you for the report, i updated the [release](https://github.com/Aelto/tw3-random-encounters-reworked/releases/tag/v3.0) assets to include the fix for the error you showed. Using the install script or installing manually again should resolve it!

It works now, thanks!

**Comment by Aelto** [comment]
You're welcome! And thanks for confirming it's working!
