### ISSUE TITLE
[BUG] RER V3.0.0 : Random game crash

### ISSUE THREAD

**Issue by HakanFly** [Aelto/tw3-random-encounters-reworked#163]
**Describe the bug**
Crash the game with a direct return to the office and a popin to send error info to CDPR.
It never takes long after loading the game and seeing the RER introduction. (about 30s)
I'm still in the prologue area (Blanchefleur).I tested with my other mods where I never had a crash.
If I deactivate the mod via mods menu, I don't have any more crash.
If I disable my other mods and leave RER enable, I crash.
If I remove all my other scripted mods (Friendly HUD, SCAAR, auto apply oil, Better Icons FR, Always full xp and Turn on the lights), I crash.

I don't know how to help you to find the problem.

**To Reproduce**
I installed the mod manually.

**Expected behavior**
Dont crash happen

**Screenshots**

**Random Encounters version used:**
 RER V3.0.0 used.

**Mods you use:**
 - Random Encounters Reworked
 - I removed all my scripted mods
 
**Additional context**
Next Gen - Last update fix patch - Dx12

**Comment by Aelto** [comment]
Thanks for the report. I read people had more chance with the dx11 backend in the meantime, i'll look into it see if i can find the reason!

**Comment by HakanFly** [comment]
Hello, no difference unfortunately.
But if I can be of any help in trying to get logs or traces to identify the issue.
I can make myself available to debug on my machine. (And speak in French)

**Comment by DOOMOlivera** [comment]
> **Describe the bug** Crash the game with a direct return to the office and a popin to send error info to CDPR. It never takes long after loading the game and seeing the RER introduction. (about 30s) I'm still in the prologue area (Blanchefleur).I tested with my other mods where I never had a crash. If I deactivate the mod via mods menu, I don't have any more crash. If I disable my other mods and leave RER enable, I crash. If I remove all my other scripted mods (Friendly HUD, SCAAR, auto apply oil, Better Icons FR, Always full xp and Turn on the lights), I crash.
> 
> I don't know how to help you to find the problem.
> 
> **To Reproduce** I installed the mod manually.
> 
> **Expected behavior** Dont crash happen
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Random Encounters version used:** RER V3.0.0 used.
> 
> **Mods you use:**
> 
> * Random Encounters Reworked
> * I removed all my scripted mods
> 
> **Additional context** Next Gen - Last update fix patch - Dx12

Yeah, It's happening to me too. I don't know if it would be related to that, but the game crashed the moment I dissabled the bounty master minimap tracker. I kept playing with that option dissabled, and about 30 minutes later the game crashed again. Maybe it's that since I've had no problem until I removed the minimap marker?

**Comment by Atarashi-Daten-Shi** [comment]
It seems setting the Mod Version to Version 3 crashes the game for some reason. In fact editing any of the settings crashes the game. If I dont edit any of the mod settings it doesnt crash

**Comment by DOOMOlivera** [comment]
> It seems setting the Mod Version to Version 3 crashes the game for some reason. In fact editing any of the settings crashes the game. If I dont edit any of the mod settings it doesnt crash

That is worse than I thought. My game doesn't crash from changing the settings but it crash when changing mod version setting to other than 0.
The worst part is that if I set mod version to 0, random enemies won't spawn. I've set the mod to spawn enemies 3 levels above me, I've played two hours and I've not seen any level 29 enemy (I'm level 26).

**Comment by TheRealJacks** [comment]
> **Describe the bug** Crash the game with a direct return to the office and a popin to send error info to CDPR. It never takes long after loading the game and seeing the RER introduction. (about 30s) I'm still in the prologue area (Blanchefleur).I tested with my other mods where I never had a crash. If I deactivate the mod via mods menu, I don't have any more crash. If I disable my other mods and leave RER enable, I crash. If I remove all my other scripted mods (Friendly HUD, SCAAR, auto apply oil, Better Icons FR, Always full xp and Turn on the lights), I crash.
> 
> I don't know how to help you to find the problem.
> 
> **To Reproduce** I installed the mod manually.
> 
> **Expected behavior** Dont crash happen
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Random Encounters version used:** RER V3.0.0 used.
> 
> **Mods you use:**
> 
> * Random Encounters Reworked
> * I removed all my scripted mods
> 
> **Additional context** Next Gen - Last update fix patch - Dx12

I have the same issue on my side. The game will randomly crash so I have no way to pinpoint exactly what could be causing it. I run no other mods, only this one, but hopefully that helps a little bit. Thank you for all the work you do on this amazing mod by the way, it's my Fav Mod of all time! Also I hope you have a wonderful Christmas if you celebrate it!

**Comment by Atarashi-Daten-Shi** [comment]
> > **Describe the bug** Crash the game with a direct return to the office and a popin to send error info to CDPR. It never takes long after loading the game and seeing the RER introduction. (about 30s) I'm still in the prologue area (Blanchefleur).I tested with my other mods where I never had a crash. If I deactivate the mod via mods menu, I don't have any more crash. If I disable my other mods and leave RER enable, I crash. If I remove all my other scripted mods (Friendly HUD, SCAAR, auto apply oil, Better Icons FR, Always full xp and Turn on the lights), I crash.
> > I don't know how to help you to find the problem.
> > **To Reproduce** I installed the mod manually.
> > **Expected behavior** Dont crash happen
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Random Encounters version used:** RER V3.0.0 used.
> > **Mods you use:**
> > 
> > * Random Encounters Reworked
> > * I removed all my scripted mods
> > 
> > **Additional context** Next Gen - Last update fix patch - Dx12
> 
> I have the same issue on my side. The game will randomly crash so I have no way to pinpoint exactly what could be causing it. I run no other mods, only this one, but hopefully that helps a little bit. Thank you for all the work you do on this amazing mod by the way, it's my Fav Mod of all time! Also I hope you have a wonderful Christmas if you celebrate it!

The Cause of the mod Crashing is Editing the Mod Version mainly but I also seems to be editing any of the mod settings

**Comment by Aelto** [comment]
At the moment simply breathing seems to cause a crash. I'm trying to find why but it's very user specific, some users get  random crashes like you and some get a perfectly running mod. It's a mystery and completely random.

Could you share the platform (GOG, Steam, ...) you use? Maybe there is something specific in one of the exes they shipped.

**Comment by DOOMOlivera** [comment]
> At the moment simply breathing seems to cause a crash. I'm trying to find why but it's very user specific, some users get random crashes like you and some get a perfectly running mod. It's a mystery and completely random.
> 
> Could you share the platform (GOG, Steam, ...) you use? Maybe there is something specific in one of the exes they shipped.

I play the epic games version, but Iaunch it with steam adding a non steam game, so I can use steam imput features.

**Comment by TheRealJacks** [comment]
I play on the Steam Version & I used the install script for the mod, I
didn't download manually.

**Comment by Atarashi-Daten-Shi** [comment]
I have a theory... Maybe its because of the Script install?

**Comment by DOOMOlivera** [comment]
> I have a theory... Maybe its because of the Script install?
> 
> Edit: Nope happens with the Manual Install as well

I initially did it with the script install, but had a merge error taht I reported here and it was adressed in the zip version, so I ended up installing it manually.

**Comment by Atarashi-Daten-Shi** [comment]
This is really frustrating because I want to play this mod on the Next Gen Update and I just cant seem to find a damn fix for it.

**Comment by Atarashi-Daten-Shi** [comment]
SOMEONE HAS FOUND A FIX!!!! Disable Static Encounters completely in the Encounter>General Settings of the Mod!

**Comment by TheRealJacks** [comment]
> SOMEONE HAS FOUND A FIX!!!! Disable Static Encounters completely in the Encounter>General Settings of the Mod!

This worked for me as well!! Thank you for the heads up fam! Good luck on the path!

**Comment by Aelto** [comment]
The "fix" is a workaround. It resolves the crash but doesn't remove the root cause. So keep in mind you may still see undefined behavior from the mod. I'm still trying the pinpoint the actual error!

**Comment by DOOMOlivera** [comment]
> The "fix" is a workaround. It resolves the crash but doesn't remove the root cause. So keep in mind you may still see undefined behavior from the mod. I'm still trying the pinpoint the actual error!

At least we now know it probably has to do with static encounters

**Comment by TheRealJacks** [comment]
> The "fix" is a workaround. It resolves the crash but doesn't remove the root cause. So keep in mind you may still see undefined behavior from the mod. I'm still trying the pinpoint the actual error!

I agree 100%, but at least now we know that static encounters could be part of the issue. Hopefully this makes you're search for the culprit a little easier though.

**Comment by DOOMOlivera** [comment]
Been playing for a while with the last update and even with static encounters on, the crashesh seem to be gone :)
