### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by DOOMOlivera** [Aelto/tw3-random-encounters-reworked#166]
When I start playing (don't know if loading saves does this too) there is no music at all. Not even in combats. I have to wait 20 minutes or so, or go to a quest that triggers a specific music for it to start playing music.

**Comment by Aelto** [comment]
This is quite a unique bug, the mod doesn't really edit sounds so i wonder if it related at all. I'll look into it but no promises!

**Comment by DOOMOlivera** [comment]
It could also be the game itself, I've heared that some people had this issue too, I think it has been fixed now, I just had to keep playing more, but it could come back

**Comment by DOOMOlivera** [comment]
Yeah, pretty sure it was a vanilla glitch
