### ISSUE TITLE
[BUG] Mod barely Spawns Encounters

### ISSUE THREAD

**Issue by Atarashi-Daten-Shi** [Aelto/tw3-random-encounters-reworked#172]
**Describe the bug**
TBH Idk if this is a bug but just in case. I cant seem to get Random Encounters to spawn frequently. Theyre so rare that it takes like 5 mins between each encounter and theyre usually just Foglets, Nekkers, Alghouls and Endregas. Nothing super out of the ordinary. If im using a setting wrong please let me know. Id love to use this mod to its fullest per-say.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Random Encounters version used:**
 RER V3.0.0 used.

**Mods you use:**
 - Random Encounters Reworked
 - FHUD
 - SCAAR
 - Critical Slow Motion Combat REDUX
 - Stack Your Items
 - Face Them
 - Smooth Camera
 - XP Multiplier
 - Perks Always Active
 - Friendly Meditation
 - QuickSave Menu
 - Fast Travel Anywhere
 - AutoApplyOils
 - AutoLoot
 - Jump In Shallow Water

**Additional context**

**Comment by DOOMOlivera** [comment]
> **Describe the bug** TBH Idk if this is a bug but just in case. I cant seem to get Random Encounters to spawn frequently. Theyre so rare that it takes like 5 mins between each encounter and theyre usually just Foglets, Nekkers, Alghouls and Endregas. Nothing super out of the ordinary. If im using a setting wrong please let me know. Id love to use this mod to its fullest per-say.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Random Encounters version used:** RER V3.0.0 used.
> 
> **Mods you use:**
> 
> * Random Encounters Reworked
> * FHUD
> * SCAAR
> * Critical Slow Motion Combat REDUX
> * Stack Your Items
> * Face Them
> * Smooth Camera
> * XP Multiplier
> * Perks Always Active
> * Friendly Meditation
> * QuickSave Menu
> * Fast Travel Anywhere
> * AutoApplyOils
> * AutoLoot
> * Jump In Shallow Water
> 
> **Additional context** Add any other context about the problem here.

It was like thaat for me as well, I just had to keep playing and eventually the mod started to spawn the enemies properly.

**Comment by Atarashi-Daten-Shi** [comment]
> > **Describe the bug** TBH Idk if this is a bug but just in case. I cant seem to get Random Encounters to spawn frequently. Theyre so rare that it takes like 5 mins between each encounter and theyre usually just Foglets, Nekkers, Alghouls and Endregas. Nothing super out of the ordinary. If im using a setting wrong please let me know. Id love to use this mod to its fullest per-say.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Random Encounters version used:** RER V3.0.0 used.
> > **Mods you use:**
> > 
> > * Random Encounters Reworked
> > * FHUD
> > * SCAAR
> > * Critical Slow Motion Combat REDUX
> > * Stack Your Items
> > * Face Them
> > * Smooth Camera
> > * XP Multiplier
> > * Perks Always Active
> > * Friendly Meditation
> > * QuickSave Menu
> > * Fast Travel Anywhere
> > * AutoApplyOils
> > * AutoLoot
> > * Jump In Shallow Water
> > 
> > **Additional context** Add any other context about the problem here.
> 
> It was like thaat for me as well, I just had to keep playing and eventually the mod started to spawn the enemies properly.

I played for about an Hour and still nothing

**Comment by Aelto** [comment]
Thanks for the report! I'll look into it, i'm guessing this is one of the consequences of the deep and unknown loading issue there is in RER NextGen.

**Comment by Atarashi-Daten-Shi** [comment]
So I got it to work but once I fast Traveled outside of Velen/Novigrad it just stopped working. I got out of the game and Reloaded back in and it still didnt work. Its like a Chance of it working

**Comment by DOOMOlivera** [comment]
> So I got it to work but once I fast Traveled outside of Velen/Novigrad it just stopped working. I got out of the game and Reloaded back in and it still didnt work. Its like a Chance of it working

Same here, It was spawning things normally, then I fast traveled to keep going with quests and the mod didn't spawn anything from that point.

**Comment by DOOMOlivera** [comment]
Since the last update I am encountering much more monsters than before, so it seems like it works now.

**Comment by XxFallenAngelxX** [comment]
I still get noting to spawn with jacked up settings, default game as well.
