### ISSUE TITLE
[BUG] MOD installed but not getting notification for preset selector. mod option menu is also not present in the game options menu,

### ISSUE THREAD

**Issue by janakrajsrivastava** [Aelto/tw3-random-encounters-reworked#173]
**Describe the bug**
MOD installed but not getting notification for preset selector. mod option menu is also not present in the game options menu,

**To Reproduce**

**Expected behavior**

**Screenshots**

**Random Encounters version used:**
 RER V3.0.0 used.

**Mods you use:**
 - Random Encounters Reworked
 

**Additional context**
MOD installed but not getting notification for preset selector. mod option menu is also not present in the game options menu,
Manually installed by extracting the archive in installation folder (next gen) and used script merger to merge the conflicts. No other mod was used. Script compiled successfully. When loading a save I am NOT getting the preset selector. Nor any option menu for the mod is present in the in-game option menu.

**Comment by TheRealJacks** [comment]
Head to you're PC folder within you're Witcher Game folders (Below)
Steam\steamapps\common\The Witcher 3\bin\config\r4game\user_config_matrix\pc

 Copy the name of the "RER" XML file (modRandomEncountersReworked.xml) 

Paste it within either "dx11filelist.txt" or "dx12filelist.txt" depending witch one you use.

It should look like this
-
audio.xml;
gameplay.xml;
hidden.xml;
hud.xml;
input.xml;
localization.xml;
gamma.xml;
display.xml;
graphics.xml;
modRandomEncountersReworked.xml;
-
The Mod menu will appear after.

**Comment by Aelto** [comment]
Exactly! I also made the [menu filelist updater](https://github.com/Aelto/tw3-menufilelist-updater) if you prefer automatic updating of the filelists
