### ISSUE TITLE
Contracts: Can Only get Bandits + Crashes when looking for Bounty Masters

### ISSUE THREAD

**Issue by maribin000** [Aelto/tw3-random-encounters-reworked#174]
When I'm at a notice board, no matter what contract I chose, it only spawned bandits for me to fight. Tried multiple locations of notice boards, only bandits spawned

When I got to the Bounty Master to trade my trophies, no one is in the area no matter how hard I look and after a minute or so, my game crashes. did those multiple times and they all crash.

 RER V3.0.0 used.

**Comment by Aelto** [comment]
Hello!

Thanks for the report, it looks like another issue related to the next-gen version only. I'll look into it!
