### ISSUE TITLE
[BUG] Bounty Master no longer appearing

### ISSUE THREAD

**Issue by preachergeneric** [Aelto/tw3-random-encounters-reworked#196]
**Describe the bug**
After updating to 3.1.3 from 3.1.2 the Bounty Master seems to be missing, I can't find his icon on any map and he no longer appears as a selectable pin in the filter. Notice boards function as expected and Contract locations still appear correctly on the map and in the map pins.

**To Reproduce**
1. Attempt to locate the bounty master on the map.

**Expected behavior**
The bounty master should appear on the map, and should have a pin on the world map that can be used to quickly jump to his location.

**Screenshots**
![image](https://github.com/Aelto/tw3-random-encounters-reworked/assets/134238040/ab9b47b8-9d80-48aa-ae1c-55370502bb3a)

Screenshot of the map without a bounty master pin. Player location is where i am teleport to after using the` rergotobountymaster` console command
**Random Encounters version used:**
 RER V3.1.3 used.

**Mods you use:**
 - Random Encounters Reworked
 - W3EE Redux
 - Darker Nights Next Gen
 - Gwent Redux
 - SharedUtilies
 - SharedImports

**Additional context**
Running the `rerkillbountymaster` does not seem to make a new one spawn. The bounty master is still missing if I load an earlier save and attempt to teleport to him with the command, and still brings me to the same location featured in the screenshot.

**Comment by preachergeneric** [comment]
After performing a clean reinstallation of the mod, using the 'rerkillbountymaster` command followed by `rerslowboot(false)` and finally `rergotobountymaster` I was able to relocate the bounty master outside of Blackbough. However, he no longer appears on the map as an excalamation point with an area around him, but instead as a standard shopkeeper. 
![image](https://github.com/Aelto/tw3-random-encounters-reworked/assets/134238040/71b214ef-c0db-40a1-bce2-0c7505610feb)

**Comment by Aelto** [comment]
Thank you for the detailed report! I've had other people reporting the exact same issue, and indeed from your testings it seems the map pin is missing Velen no matter what you do. The sharedutils_mappins module was updated recently to prepare the next release so it's possible something broke inside RER because of that!

_I am currently away so i will probably take care of this issue later this week or next week._
