### ISSUE TITLE
[FEATURE] Setting to turn off 'Lower Reputation On Deaths'

### ISSUE THREAD

**Issue by Ghostdreamer11** [Aelto/tw3-random-encounters-reworked#198]
pull #133 added tracking deaths when completing contracts. However, this can be very punishing if you are playing with other mod packs (W3ee Redux looking at you) especially when first starting out/figuring out the game. 

**Describe the solution you'd like**
Add a setting for how much reputation is lost when you die on a contract (from 0 to .. whatever). Those that wish to disable this feature can turn it to 0. Those that don't can chose their acceptable level of punishment. 

**Describe alternatives you've considered**
Add a setting to disable this feature entirely. 
Turning off the reputation system (which I don't particularly like, because then you can't turn on the 'vanilla contracts a X reputation' feature which encourages more interaction.)

**Comment by Aelto** [comment]
Thank you for the detailed issue! This is a good idea. It is implemented now as you can see from the recent commit. Only testing is needed at the moment, which i won't be able to do before next week
