### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LuckyIrishLad** [Aelto/tw3-random-encounters-reworked#200]
**Describe the bug**
Whenever I start a new game the mod is shown as enabled, but the bounty master doesn’t appear nor do any notice board quests. (Enhanced Version)

**To Reproduce**
1. Start New Game

**Expected behavior**
Clarification if it is something I’m doing wrong or just a bug

**Screenshots**

**Random Encounters version used:**
 RER 3.02

**Comment by Aelto** [comment]
Hello! How far are you in the game in terms of playtime? If you're just starting the mod has a "slow boot" feature where its core features get activated over time to avoid overwhelming you

**Comment by LuckyIrishLad** [comment]
It’s a relatively fresh save. I would say maybe like almost an hour. I had a previous save that I downloaded the mod mid-game, and the notice board bounties appeared almost instantly. Is it based off when you install the mod or how long you have played on a particular save?

**Comment by Aelto** [comment]
Yes, as stated in my previous comment these features are activated only after a few hours of gameplay. It's usually when you're ready to leave White Orchard and that you're fully clearing it, so about 4 or 5 hours of gameplay. After that and after a full reload of your save the mod will add the bounty master, the contracts, the events, the encounters, etc....

**Comment by LuckyIrishLad** [comment]
Okay thanks for your help!
