### ISSUE TITLE
[BUG] Already imported components in mod_sharedutils_npcInteraction/content/scripts/engine/components.ws

### ISSUE THREAD

**Issue by jmattspartacus** [Aelto/tw3-random-encounters-reworked#201]
**Describe the bug**
Fresh install script compilation fails because the components

CSoundAmbientAreaComponent, CDestructionComponent, CClothComponent, CDestructionSystemComponent 

are already imported in ...mods/mod_sharedutils_npcInteraction/content/scripts/engine/components.ws

**To Reproduce**
1. Download latest release (3.2 as of writing) 
2. With no other mods installed, copy paste the extracted contents into the game folder.
3. Run game, see compilation fails

**Expected behavior**
Game launches with no issues

**Random Encounters version used:**
 RER V3.2.0 used.

**Mods you use:**
 - Random Encounters Reworked

**Additional context**
On Linux, I don't believe this should have any bearing on the issue. I was able to get the game to launch by commenting out the mentioned components. Have not done further testing yet.

**Comment by Aelto** [comment]
Hello, you are supposed to merge the scripts after installing mods. You can use the [Script Merger](https://www.nexusmods.com/witcher3/mods/484) that will do it for you.

**Comment by jmattspartacus** [comment]
Ope, my bad, new to Witcher 3 modding, I'll close this.

**Comment by Aelto** [comment]
No worries, have fun with the mod(s)!
