### ISSUE TITLE
[BUG] Script Compilation Errors with tw3 v4.04

### ISSUE THREAD

**Issue by Cl4ySmith** [Aelto/tw3-random-encounters-reworked#205]
**Describe the bug**
I updated this mod to v3.03, however Script Compilation Errors occured.

Here is the errors log.

Error [mod0000_mergedfiles]game\player\playerinput.ws(1391): Could not find function 'GetRadialPopupShown'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1398): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1400): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1414): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1416): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1499): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1502): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1505): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1508): Could not find function 'PotionSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1530): Could not find function 'OilSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1534): Could not find function 'OilSelectionPopup'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1558): Could not find function 'GetRadialPopupShown'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1592): Could not find function 'GetRadialPopupShown'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1624): Could not find function 'GetRadialPopupShown'
Error [mod0000_mergedfiles]game\player\playerinput.ws(1653): Could not find function 'GetRadialPopupShown'
Error [content0]game\gui\popups\itemselectionpopup.ws(289): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(300): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(311): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(322): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(333): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(345): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(394): Could not find function 'EnableRadialInput'

Warning [modsharedimports]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
Warning [modsharedimports]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.

**Screenshots**
![image](https://github.com/Aelto/tw3-random-encounters-reworked/assets/80500763/e3bba13b-d4e7-48f2-a05f-e0b2b9826a6b)
![image](https://github.com/Aelto/tw3-random-encounters-reworked/assets/80500763/beb6be95-7730-47c0-8f2b-6bd67f4c0b35)

**Random Encounters version used:**
 RER V3.03 used.

**Mods you use:**
 - Random Encounters Reworked
mod0000_MergedFiles
mod00MapQuestObjectives_SGUI
modBasicCookingRecipes
modConvenientLooting
modMapQuestObjectivesFull
modMiniMapMoreArea
modNoWeightLimit
modRandomEncountersReworked
modSharedImports
modSmoothGUI
mod_sharedutils_damagemodifiers
mod_sharedutils_dialogChoices
mod_sharedutils_glossary
mod_sharedutils_helpers
mod_sharedutils_mappins
mod_sharedutils_noticeboards
mod_sharedutils_npcInteraction
mod_sharedutils_oneliners
mod_sharedutils_storage
mod_sharedutils_tiny_bootstrapper

**Additional context**
This mod is great, thanks for your work!

**Comment by Aelto** [comment]
The other mods you use a probably not updated to 4.04
