### ISSUE TITLE
[BUG]  mutagens wont be cost while cooking decoctions in W3EER

### ISSUE THREAD

**Issue by zxcvbnm3057** [Aelto/tw3-random-encounters-reworked#222]
**Describe the bug**

**To Reproduce**
please check the attached video.

**Expected behavior**

**Screenshots**

**Random Encounters version used:**
 RER V3.3 used.

**Mods you use:**
 - Random Encounters Reworked
 - w3ee redux V1.39b

**Additional context**

https://github.com/Aelto/tw3-random-encounters-reworked/assets/48760372/5a66b59c-01e4-463d-a4a3-0dbe5753bdd3

**Comment by zxcvbnm3057** [comment]
Any of archetype mutagens wont be cost. And it should in w3ee redux

**Comment by Aelto** [comment]
I don't understand, is there anything related to RER?

**Comment by zxcvbnm3057** [comment]
sorry... it seams i misunderstand w3ee decoctions...

**Comment by zxcvbnm3057** [comment]
but is it normal that the enemy i found in my bounties or tracks hunting is really hard to kill. Their health are almost 1 million and 
cause 7000 damage on one attack. Or is their a setting can modify it?

I selected the w3ee redux mode. And im in very early game now, i just got Velen about 2 hour ago
