### ISSUE TITLE
Latest RER version installed  - Yet am not getting the preset choices when i Load my save game - Next Gen 4.04

### ISSUE THREAD

**Issue by DonAlem** [Aelto/tw3-random-encounters-reworked#223]
Hello,
Appreciate the help, please. 
game version 4.04

I first downloaded manual followed the steps correctly and no error or issue, mod menu is ingame. yet when i loaded my last save yet the preset choice didn't pop-up waiting for few min and nothing.
So i followed the steps to uninstall and it worked (even got the notification message return when using the commands with the console: rerabandonbounty & reruninstallon)

Then I have downloaded the mod using the script file "Install-mod", and used the menulist tool for to game meu and script merge and no issue no error.
Loaded my last save and still waited longer this time and still no pop-up for the preset choice,

both times i pressed the "get preset selection" on the RER mod menu still nothing, tried to enable the mod and again press that button still no preset, so am not sure if mod is working should i keep it an play and test or i risk to corrupt playthough ?

Thank you in advance!

**Comment by Aelto** [comment]
Hello!

Could you please confirm the `playerInput.ws` has a pending merge with at least `sharedutils_tinybootstrapper` in it. This file should be merged, and the sharedutils code should be included in the resulting merge. If it isn't included then you'll be left in your current situation where RER is installed but not running.

**Comment by DonAlem** [comment]
Hey Aelto,

Thanks for feedback, i did remove it yesterday, i did an install with the script now and used the menulist tool to enable the menu, now i will do the merges, what i usually do when i do a new mod i delete all merges and create a fresh one for all, should i do that or just merge what i currently have after installing the RER ? 

![RER Merge](https://github.com/Aelto/tw3-random-encounters-reworked/assets/160198324/dff23ac4-4465-4569-91b3-fb8b545a73e3)

**Comment by Aelto** [comment]
you can simply merge what's shown on the left, as long as you merge everything it should be fine

**Comment by DonAlem** [comment]
Thanks, I did that, and no error (perfect auto merge)
Let me test and provide feedback
![After Merge](https://github.com/Aelto/tw3-random-encounters-reworked/assets/160198324/e60718d1-88d4-4183-92c4-3c7cb2803850)

**Comment by DonAlem** [comment]
It worked this time got the popup to choose preset.
well, i didn't get to choose since i was stupid and wanted to take a screenshot and pressed the windows faster than pressing Shift+S :( ,  so the game went to the pause menu and lost the preset choice popup- however this time in the mod menu i see it automatically set to ON unlike the previous 2 tries so I assume now it's working and i can set the settings for the mode form the RER menu itself to whatever i like right?

**Comment by DonAlem** [comment]
Hi again,
now I have a weird issue when i get the pop menu to choose a bounty or at the bounty master the curser remains visible on screen after am done with the choice, have to save and reload for it to disappear

**Comment by Aelto** [comment]
Hi, good to hear you managed to get it running. I'm closing the issue since the reason it was opened is now solved.

As for the cursor bug, unfortunately this is a known issue that i cannot replicate nor solve (since it's hard to solve if i can't replicate it) but i'm aware of it. You can follow the related issue #199
