### ISSUE TITLE
[BUG] Can't get into from the launcher.

### ISSUE THREAD

**Issue by punktown94** [Aelto/tw3-random-encounters-reworked#224]
**Describe the bug**

Hello Please to meet you and thanks for this amazing mods which I need(as mentioned in description)'
Unfortunately I am unable to play this, because I have crash? below (v)

|
Error [modsharedimports]local\cclothcomponent.ws(7): Class 'CClothComponent' was already exported.
Error [modsharedimports]local\cdestructioncomponent.ws(50): Class 'CDestructionSystemComponent' was already exported.
Error [modsharedimports]local\cdestructioncomponent.ws(118): Class 'CDestructionComponent' was already exported.
Error [modsharedimports]local\csoundambientareacomponent.ws(31): Class 'CSoundAmbientAreaComponent' was already exported.
|

In case about my game situation, I use one mods that change Geralt to Mads Mikkelson design.
So I thought this give crashes so I uninstall it but still have the same issues.

To be honest I am no good and ignorance of this part(Coding and Merging)
So I would like to ask you to fixational advice kindly.

Whats should I do?

**Screenshots**

![화면 캡처 2024-03-15 174713](https://github.com/Aelto/tw3-random-encounters-reworked/assets/35885739/a71c2ab9-58f8-42ec-b1b7-9f4bce410154)

**Random Encounters version used:**
 RER V3.3 used.

**Mods you use:**
 - Random Encounters Reworked
 - Mads Mikkelsen face mod (by. Lascaroman) ; https://www.nexusmods.com/witcher3/mods/4314
 - Ultimate Netflix Henry Cavill Mod (by. Bjorn18) ; https://www.nexusmods.com/witcher3/mods/8931_not installed, keep
 - Cut-throat Razot (by. paulr0013) ; https://www.nexusmods.com/witcher3/mods/7858_not installed, keep

**Additional context**

**Comment by punktown94** [comment]
Since I am marathoning the Vanila Story and whole world so please take your time and hope for you see this.
Again, Thanks for this amazing and creative minds

**Comment by punktown94** [comment]
Okey I handle over launcher by merger(Hope I done right XD)
But another problem is that, I can't see mod menu... I see it shows the choice when I into saved game wonder that mods are applied or not

**Comment by Aelto** [comment]
Hello, yes merging the scripts was the right solution. Then you need to update your menu filelists. The in-depth guides have a section about it if you're not sure of how to do it

**Comment by punktown94** [comment]
Yes I did all! and thank you so much! problem is now translation part and sometimes few board mission's are unwritten but...
this is not this matter so the origin problem is all done! Thanks so much!
Maybe I'll do the traslation if I figure how to fix this.
