### ISSUE TITLE
[BUG] Bounties doesn't work

### ISSUE THREAD

**Issue by kappacite** [Aelto/tw3-random-encounters-reworked#230]
When I take a bounty from the Bounty Master, it gave me a bounty " Unknown ". When I go to the Bounty Zone, it get cleared immediatly and gives me nothing in reward.

**To Reproduce**
1. Go to Bounty Master
2. Click on Start a Bounty
3. Go to the Bounty Zone
4. Get Bounty cleared and nothing in reward.

**Expected behavior**
Get a real monster / group of monsters to kills and a reward.

**Screenshots**
![image](https://github.com/user-attachments/assets/ddd5eceb-3e68-4e95-a49f-5c563cd0be88)
![image](https://github.com/user-attachments/assets/b58b1c6d-ed92-4b91-b834-ff2dcfcb0974)
(I just entered the zone, not killed anything)

**Random Encounters version used:**
Latest, installed with the install script.

**Mods you use:**
 - Random Encounters Reworked
 - GwentRedux
 - FriendlyMeditation
 - FriendlyHUD
 - Preparations Mod
 - ESGO
 - Reputation System
 - True Aerondight
 - Weapon Oils Vanilla Plus
 - E3 Quen
 - Better Igni NG
 - Better Trophies
 - Blood Trail
 - Elysium NG
 - 4k Soft Clouds
 - 4k Story Characters
 - Agressive Enemies
 - Another Quen
 - Cozier Fires
 - Enhanced Water
 - Eye Cat
 - HD Monsters Reworked
 - HQ Faces
 - Menu Strings
 - Mutagen Overhaul
 - New Clouds
 - Quest Edit Cam Light
 - Realistic Weather
 - SCAARAIO
 - 4k Armor Textures
 - Volumetric Clouds

**Comment by Aelto** [comment]
Hi !

The unknown monster could indicate that you're missing the mod menu or that your current settings stopped RER from finding a valid species. For example region constraints could stop everything from spawning in white orchards.

The lack of rewards could also come from a missing menu or custom settings. Bounties give random items every levels, then on multiples of 5, so 5, 10, 15, 20, ... You get a special milestone reward. They're usually inserted straight into your inventory.

If you're missing a mod menu I would recommend updating your filelists, there d a section about them in the in depth guide if you need !

**Comment by kappacite** [comment]
Thank's for your answer.

I got the mod menu in my games and in my settings, every mob is allowed to spawn & can spawn everywhere.

I've checked the in-depth guide but I've already did all that is written.
I've also tried to reinstall the mod but It didn't changed anything.
