### ISSUE TITLE
[BUG] Wild hunt warriors target their own hounds.

### ISSUE THREAD

**Issue by Sneakpeakcss** [Aelto/tw3-random-encounters-reworked#72]
**Describe the bug**
Wild hunt ambush has a tendency to attack their own hounds after being summoned.

**To Reproduce**
1. rera(CreatureWILDHUNT)
2. Stay far away from them or roll around.

**Expected behavior**
They should be a bit more friendly towards each other.

**Screenshots**
https://i.imgur.com/uEuzu1S.mp4

**Random Encounters version used:**
 RER V2.5 used.

**Mods you use:**
 - Random Encounters Reworked

**Additional context**
It looks like warriors switch target to their own hounds if they can't attack geralt for one reason or another, hounds sometimes swing back at them, but they don't actively target them and focus properly on attacking geralt.

**Comment by Aelto** [comment]
The bug is now resolved, a solution was found. Wild hunt soldiers no longer target their hounds.

Thanks for the report!
