### ISSUE TITLE
[BUG] error while compiling

### ISSUE THREAD

**Issue by RubenKelevra** [Aelto/tw3-random-encounters-reworked#81]
**Describe the bug**
I've used the install script, have run the merger and now the game shows this error while starting:

```
Error [modbootstrap-registry]local\mods_registry.ws(3): Unknown base class 'CModFactory'
Error [modrandomencountersreworked]local\rer_scripts.min.ws(1646): Unknown base class 'CEntityMod'
Error [modrandomencountersreworked]local\rer_scripts.min.ws(26178): Unknown base class 'IModStorageData'
```

**To Reproduce**
1. Run script
2. Run script merger
3. Start game

**Expected behavior**

**Screenshots**

**Random Encounters version used:**
unknown

**Mods you use:**
 - Random Encounters Reworked
 - many (how do I export a list in vortex?)

**Additional context**

**Comment by Aelto** [comment]
Hello,

You already had bootstrap installed but used an old version of the mod, for this reason the install script did not download the latest version to avoid breaking your current modlist. You can find the link to the latest bootstrap version [here](https://aelto.github.io/tw3-random-encounters-reworked/indepth-guide/#part-1-1)

**Comment by HER011** [comment]
Hi I have a similar issue but with the current version pf the bootstrap. The message I get is the following "Error [modbootstrap]local\bootstrap\utils\bootstrap.ws(38): Unknown type 'CModRegistry' for property 'modRegistry'."

**Comment by Aelto** [comment]
Hello,

refer to [this part of the guide](https://aelto.github.io/tw3-random-encounters-reworked/indepth-guide/#part-1-1) on how to install bootstrap. There are two parts and you only installed one of the two.
