### ISSUE TITLE
Polish Strings

### ISSUE THREAD

**Issue by ADawesomeguy** [Aelto/tw3-random-encounters-reworked#98]
Nothing more than they just haven't been updated. @SpontanCombust 👀 caught slackin.

**Comment by SpontanCombust** [comment]
I don't update the strings until the next mod version comes out of the pre-release phase, because if I did obviously ANYTHING might get changed in the process anytime and I would have to keep correcting stuff EVERY time.
Be more mindful of that the next time you mention me @ADawesomeguy

**Comment by ADawesomeguy** [comment]
Oh I was just kidding around, I didn't realize 2.8 was still prerelease, sorry.

**Comment by Aelto** [comment]
It is not, but it could very well be a pre-release indeed. I wrote in the official discord server that i lack the time to do proper testing on this one unfortunately,

**Comment by ADawesomeguy** [comment]
Eh who cares about testing anyways. That's the end users' job.
